"""rename department

Revision ID: 82a42e29c5f8
Revises: f6a5b1c495a2
Create Date: 2025-01-15 19:35:52.070485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82a42e29c5f8'
down_revision = 'f6a5b1c495a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.rename_table('departments', 'department')
    # ### end Alembic commands ###
